# Generated by Django 6.0.5 on 2026-05-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikename', models.CharField(max_length=100)),
                ('fueltank_capacity', models.FloatField(help_text='Fuel tank capacity in liters')),
                ('average_mileage', models.FloatField(help_text='Average mileage in km/liter')),
                ('starting_location', models.TextField()),
                ('destination_location', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
