# Generated by Django 6.0.5 on 2026-05-31 14:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0002_tripsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biketrip',
            name='average_mileage',
        ),
        migrations.RemoveField(
            model_name='biketrip',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='biketrip',
            name='fueltank_capacity',
        ),
        migrations.RemoveField(
            model_name='biketrip',
            name='starting_location',
        ),
        migrations.AddField(
            model_name='biketrip',
            name='destination_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketrip',
            name='destination_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='biketrip',
            name='starting_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='biketrip',
            name='starting_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='RouteWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('bike_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_points', to='bike_app.biketrip')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
